### ISSUE TITLE
ER diagram is empty

### ISSUE THREAD

**Issue by mdear** [kkrisz1/staruml-reverse-db#113]
I ran this module and saw all tables being traversed in my database and a model was created on StarUML containing all my tables. 

However, the resulting diagram was empty.

Am I expected to drag and drop all the tables to create this diagram, or should this module create the diagram for me, including auto-routing of table interconnects ?

[StarUML_ReverseDbDebugConsole.txt](https://github.com/kkrisz1/staruml-reverse-db/files/10857943/StarUML_ReverseDbDebugConsole.txt)

**Comment by kkrisz1** [comment]
Yes, you have to create a canvas and drag-and-drop the tables. The connection between the tables will be drawn automatically

**Comment by kkrisz1** [comment]
FYI

[Draw ER Diagram](https://github.com/kkrisz1/staruml-reverse-db/blob/master/draw-er-diagram.gif)

I hope it helps. 
I close the issue.
