### ISSUE TITLE
could you please generate base informations when there is no foreign relations between tables?

### ISSUE THREAD

**Issue by grdk37** [kkrisz1/staruml-reverse-db#12]
hi,this plugin is great & excellent,i appreciate it 
    when i connect to MySQL 5.7, in the settings page, there is a schema and a database,these confuses me . 
    i think it would be better if it had a 'test connection button ';
    and when clicking the ' generate ER data model ' , sometimes it just say ' there is an error', i think it would be better if it showed the actual error.  then i can google it ,or change the exact wrong place 
    what i need most    is   as the title, generate something even if there is no foreign relations,
or  could you please provide a radio button ,so that it will not bother the person who don't need this function.  
    thank you so much

**Comment by kkrisz1** [comment]
hi,
what kind of default information do u think?
p.s.: yes, error handling improvement is needed
-krisz

**Comment by kkrisz1** [comment]
Can close the issue cause of unprecise requirement?
(If there is no foreign key, it will not make sense to add default information about relationship between tables)
