### ISSUE TITLE
No ERD is generated when connecting to a Postgres database

### ISSUE THREAD

**Issue by xinix** [kkrisz1/staruml-reverse-db#13]
I'm trying to generate an ERD of a postgres database. I am running a vagrant box (homestead) with a postgres database, that has some tables in it. When I generate  the data model, two messages appear: `ER Data Model generation has been started. Please wait...` and `ER Data Model generation has been finished`.  In the model explorer an item was added with a database icon, but no tables or ERD schema was generated. 

I'm running StarUML 2.8.1 on Windows and version 0.2.1 of this extension.

**Comment by korridor** [comment]
I have the same problem on macOS Sierra with MySQL.
I also have StarUML 2.8.1, the messages are the same and I also get an empty database icon.

**Comment by einsty** [comment]
I too am seeing a similar issue with macOS Sierra and SQL Server.

**Comment by kkrisz1** [comment]
If you are **using MySQL**, make sure you do not change **"Database" preference**. It **has to be "def"**.
Database means "TABLE_CATALOG"
Database Schema means "TABLE_SCHEMA"
![macossierra_mysql_schemainfo](https://user-images.githubusercontent.com/19638316/38424221-a02cf41a-39b0-11e8-83c4-651cf1095bac.PNG)

I know that it is a bit confusing, I will fix it later

**Comment by kkrisz1** [comment]
Please let me know If the above comment solve the problem

**Comment by sekanitembo** [comment]
I'm running into this on Win10/SQL Server. I can't seem to find a combination of database/database schema that will read. 

I was able to get a separate postgres db (docker container) to work by providing database schema 'public' and then relevant db name, making sure to use the host's port, not the container's.

**Comment by kkrisz1** [comment]
FYI

## [PostgreSQL: Documentation](https://www.postgresql.org/docs/current/static/ddl-schemas.html)
### 5.8.2. The Public Schema
In the previous sections we created tables without specifying any schema names. By default such tables (and other objects) are automatically put into a schema named “public”. Every new database contains such a schema. Thus, the following are equivalent:

`CREATE TABLE products ( ... );`
and:

`CREATE TABLE public.products ( ... );`

**Comment by korridor** [comment]
@kkrisz1 Thanks it's working now!
