### ISSUE TITLE
Configure Server exception

### ISSUE THREAD

**Issue by runningwaterpro** [kkrisz1/staruml-reverse-db#147]
Hi!

Click the menu (Tools > Database > MySQL Server > Configure Server...)

There was no configuration window appearing afterwards, nor any other changes. 

How should I resolve that? 

Thank you! 

![image](https://github.com/kkrisz1/staruml-reverse-db/assets/389973/6e207abc-076e-45ed-b817-c080c18a668a)

**Comment by kkrisz1** [comment]
could you try to reinstall the extension?

the module should be here: 
`c:\Users\<username>\AppData\Roaming\StarUML\extensions\user\kkrisz1.staruml-reverse-db\node_modules\lodash`

**Comment by runningwaterpro** [comment]
After I reinstalled the extension, the Preferences window appeared. 

Thank you!

**Comment by kkrisz1** [comment]
U r welcome
