### ISSUE TITLE
Does not support POSTGRESQL

### ISSUE THREAD

**Issue by duaneking** [kkrisz1/staruml-reverse-db#3]
This really should support PostgreSQL.

Supporting other DB's is a worthy goal and would turn StarUML into a competitive option to much more expensive tools.

What would it take to have you add support for PostgresSQL?

**Comment by kkrisz1** [comment]
#5 is created and merged
missings: relationship creation between entities based on the foreign keys

**Comment by kkrisz1** [comment]
Could help me to test the nre feature?

**Comment by duaneking** [comment]
Was hoping I could just export the sql with each table having its own file, and not have to connect to db.

**Comment by kkrisz1** [comment]
If I mean well, you would like to transform ERD to SQL.
Then the below StarUML extension is totally suitable for your requirement:
[PSQL (PSQL Code Generator)](https://github.com/adrianandrei-ca/staruml-postgresql)

**Comment by kkrisz1** [comment]
Ok, got it
SQL -> ERD :)

**Comment by duaneking** [comment]
Would love to use this but I had to reinstall StarUML and the latest version has a defect that doesnt let you scroll down or see your entire list of models.
