### ISSUE TITLE
MS SQL Server encrypt

### ISSUE THREAD

**Issue by ELPTFASSN** [kkrisz1/staruml-reverse-db#36]
Most Azure Databases hosted instances requires that SSL be enabled.
Currently I don't see any options to enable SSL for the MS SQL Server connection.

![image](https://user-images.githubusercontent.com/17335955/46511530-82e21580-c825-11e8-94dd-a766d57927f0.png)

Kind regards. AJW

**Comment by kkrisz1** [comment]
In progress
#37

**Comment by kkrisz1** [comment]
Release v1.0.9 contains the improvement.
Release request was sent to StarUML. It will be available in the ExtensionManager, if the request is completed.

**Comment by ELPTFASSN** [comment]
> Release v1.0.9 contains the improvement.
> Release request was sent to StarUML. It will be available in the ExtensionManager, if the request is completed.

Thank you for keeping in mind, I appreciate the time you spend on this project, best regards. AJW
