### ISSUE TITLE
Also I would like support of mysql if you will

### ISSUE THREAD

**Issue by AndyWu2015** [kkrisz1/staruml-reverse-db#4]

**Comment by kkrisz1** [comment]
The tool will generate ERD via from DB via an active connection.
Is this what you need for?
Or generate ERD offline from SQL?

**Comment by AndyWu2015** [comment]
I mean this tool can connect to mysql server and generate ERD

**Comment by kkrisz1** [comment]
Yes.
DB -> ERD conversation will be implemented.
SQL -> ERD is out of scope of the extension

**Comment by AndyWu2015** [comment]
thanks for the reply.
