### ISSUE TITLE
Can't generate ER Diagram

### ISSUE THREAD

**Issue by GitHanter** [kkrisz1/staruml-reverse-db#41]
Try to generate ER Diagram from MS SQL Server 2012 with StarUML 3.0.0. It's not work, I copied the SQL from MsSqlAnalyzer.js and execute it on SSMS, it is successfully return the tables, columns and relations. That means my server configuration is well fuction. WHAT I MISSED?

**Comment by kkrisz1** [comment]
What is the error? Are there any outputs in the log?

**Comment by liux08** [comment]
Same here, ERD generation for SQL server 2012 it's not working, it just add a diagram to the Model but always is empty. The console under developer tools shows no errors, only this 2 msgs 

-ER Data Model generation has been started. Please wait...
-ER Data Model generation has been finished.

Could you give me some help?

 Thanks!
![sql preferences](https://user-images.githubusercontent.com/11840018/46974586-4c07cd00-d079-11e8-91ea-ea39e9de6fe4.png)

**Comment by kkrisz1** [comment]
could you try the below, please?
use `master `instead of `databaseName`

I think there is no kind of `dbo` schema under `databaseName` database

![db_prefs](https://user-images.githubusercontent.com/19638316/46982277-eb5dac00-d0db-11e8-9888-e77c19c50638.PNG)

**Comment by liux08** [comment]
No effects at all, same empty ERD generated.
![sql preferences2](https://user-images.githubusercontent.com/11840018/46983845-3c977c80-d097-11e8-9b75-2704afd0d27b.png)
I cannot find the right combination of Database Schema and Table Catalog :/

![image](https://user-images.githubusercontent.com/11840018/46984053-29d17780-d098-11e8-805b-09c5a0db2b15.png)

Thanks!

**Comment by liux08** [comment]
Another clue, I executed the sql script from MsSqlAnalyzer with dbo as schema name, and it returns the schema info, what am I missing?

![image](https://user-images.githubusercontent.com/11840018/47034454-44553080-d12c-11e8-8513-e46eab74b9f0.png)

**Comment by kkrisz1** [comment]
my test settings:
```
CREATE DATABASE test;
GO
CREATE LOGIN test_user WITH PASSWORD = N'Password01#', DEFAULT_DATABASE = test;
GO
USE test;
GO
CREATE USER test_user FOR LOGIN test_user WITH DEFAULT_SCHEMA = test_user;
GO
CREATE SCHEMA test_user GRANT SELECT ON SCHEMA::test_user TO test_user;
GO
EXEC sp_addrolemember N'db_owner', N'test_user'
GO
```

for connection i use the created LOGIN user (test_user)
pls check the members of the database also

**Comment by liux08** [comment]
I executed your test script (locally and on a remote server) and I'm still not able to generate the ERD, the odd thing it's I installed mysql to try out the generator and it runs smootly with no issues :/
Thanks for your help!
![image](https://user-images.githubusercontent.com/11840018/47100635-d7ee3600-d1ec-11e8-98ae-957d4478ac47.png)
![image](https://user-images.githubusercontent.com/11840018/47100643-dae92680-d1ec-11e8-9419-0d9b97888208.png)

**Comment by kkrisz1** [comment]
did you create the tables with test_user?

pls try the below:
`/opt/mssql-tools/bin/sqlcmd -e -S localhost -l 30 -U test_user -P password01@ -i `[expecteddatamodel_table_create.sql](https://github.com/kkrisz1/staruml-reverse-db/blob/master/test/mssql/expecteddatamodel_table_create.sql)

**Comment by shahabaz** [comment]
Same situation here. The connection is perfectly fine. It creates an empty data model. Any Help!

![image](https://user-images.githubusercontent.com/4548913/47137195-8d93b480-d2d3-11e8-82ca-a06489de6987.png)

**Comment by kkrisz1** [comment]
> I did, and I got the same result an empty diagram. That's weird nothing seems to work on my sql server xD
> 
> Thanks!
> 
> ![image](https://user-images.githubusercontent.com/11840018/47110692-67eca980-d206-11e8-87b0-c076fe183f62.png)

Could you try the below? (Just guessing. I think the issue is about the permissions)

```
USE master;
GO
-- have to be the database owner (test_user) to be able to see 
-- the databases in SQL Server Management Studio if the DENY VIEW ANY DATABASE
-- is enabled 
DENY VIEW ANY DATABASE TO test_user;
GO
```
After:
```
USE master;
EXECUTE AS LOGIN = N'test_user';
GO
-- query what you want to execute. E.g.:
SELECT name FROM sys.databases WHERE HAS_DBACCESS(name) = 1;
GO
REVERT;
```
Result should be:
```
master
tempdb
```
And:
```
USE test;
EXECUTE AS LOGIN = N'test_user';
GO
-- query what you want to execute. E.g.:
SELECT name FROM sys.databases WHERE HAS_DBACCESS(name) = 1;
GO
REVERT;
```
Result should be:
```
master
tempdb
test
```

**Comment by liux08** [comment]
> > I did, and I got the same result an empty diagram. That's weird nothing seems to work on my sql server xD
> > Thanks!
> > ![image](https://user-images.githubusercontent.com/11840018/47110692-67eca980-d206-11e8-87b0-c076fe183f62.png)
> 
> Could you try the below? (Just guessing. I think the issue is about the permissions)
> 
> ```
> USE master;
> GO
> -- have to be the database owner (test_user) to be able to see 
> -- the databases in SQL Server Management Studio if the DENY VIEW ANY DATABASE
> -- is enabled 
> DENY VIEW ANY DATABASE TO test_user;
> GO
> ```
> After:
> 
> ```
> USE master;
> EXECUTE AS LOGIN = N'test_user';
> GO
> -- query what you want to execute. E.g.:
> SELECT name FROM sys.databases WHERE HAS_DBACCESS(name) = 1;
> GO
> REVERT;
> ```
> Result should be:
> 
> ```
> master
> tempdb
> ```
> And:
> 
> ```
> USE test;
> EXECUTE AS LOGIN = N'test_user';
> GO
> -- query what you want to execute. E.g.:
> SELECT name FROM sys.databases WHERE HAS_DBACCESS(name) = 1;
> GO
> REVERT;
> ```
> Result should be:
> 
> ```
> master
> tempdb
> test
> ```
I tried the queries but didn't work either, same empty diagram was generated :/

Thanks!

![image](https://user-images.githubusercontent.com/11840018/47371169-2fcce700-d69c-11e8-8053-f13a6d4fe5c9.png)

**Comment by Yashael** [comment]
Hi everyone, i found a workaround.

set the default user's db to the target db in your SQL Managment.

![image](https://user-images.githubusercontent.com/22559836/52972194-a5616f00-337f-11e9-9aea-6b7fca3cd901.png)


And it returns a set of objects like this

![image](https://user-images.githubusercontent.com/22559836/52972203-b611e500-337f-11e9-8c9c-37222ea53874.png)


Hope this help someone. cheers.
