### ISSUE TITLE
Unable to generate mysql data structure

### ISSUE THREAD

**Issue by xwqb** [kkrisz1/staruml-reverse-db#42]
Hello, the author, thank you very much for providing this plug-in. I have encountered a problem in my use. I cannot generate the data structure to mysql database, but I can get the existing structure from the database
![image](https://user-images.githubusercontent.com/11797392/50545425-597f2d00-0c4e-11e9-8393-bbdcb96db761.png)

staruml config set：
![image](https://user-images.githubusercontent.com/11797392/50545430-76b3fb80-0c4e-11e9-9d25-4edb3d43b97d.png)

def.test ERD was generated using Alt +shift+p, but could not be synchronized to mysql data

Using Alt +shift+p again generates def.test ERD
![image](https://user-images.githubusercontent.com/11797392/50545447-d3171b00-0c4e-11e9-8b2b-893a4991e5bb.png)

What method does the building advocate have

**Comment by kkrisz1** [comment]
hi,

it is a reverse engineering plugin.
it only creates DataModel based on the existing data structure in the database from scratch.

-krisz
