### ISSUE TITLE
Entity to Model with comments

### ISSUE THREAD

**Issue by JiangWenJie** [kkrisz1/staruml-reverse-db#43]
My team uses Chinese to communicate，we hope generate model can provide comments，thank you.
Sorry，my english is not good.But I hope you can give help.

**Comment by kkrisz1** [comment]
What do you mean? 
Get the comments of tables and columns from database and save them as part of the entity data model?

**Comment by kkrisz1** [comment]
may i close the issue?
have u hcecked the latest verion (1.0.11)?
