### ISSUE TITLE
Additional columns created when same named tables exist in other schemas for Postgresql

### ISSUE THREAD

**Issue by bhayes-FH** [kkrisz1/staruml-reverse-db#46]
I noticed that after running "Generate ER Data Model" for Postgresql, there were additional columns created in tables.  It turned out that the additional columns were from tables in other schemas in the database.  After looking at the SQL in postgresql/PostgreSqlAnalyzer.js, I see a bug.  I have attached a patch file for you: it adds an "AND" to the end of line 36 and inserts a new line for line 37, which adds "cls.relnamespace::regnamespace::text = col.table_schema".  I tested the query against my database (which has duplicate table names in separate schemas) and the query worked.

Thank you,
Ben

[patch.zip](https://github.com/kkrisz1/staruml-reverse-db/files/3307550/patch.zip)

**Comment by kkrisz1** [comment]
could you create a PR for this change?

**Comment by bhayesMHC** [comment]
I have created PR 47 for this.

**Comment by kkrisz1** [comment]
hi, 
sry for the late response.

could you share the details if possible?
e.g.: PostgreSQL version, DDL

**Comment by kkrisz1** [comment]
https://github.com/kkrisz1/staruml-reverse-db/pull/47 is merged

**Comment by kkrisz1** [comment]
released: [v2.1.2](https://github.com/kkrisz1/staruml-reverse-db/releases/download/v2.1.2/kkrisz1.staruml-reverse-db-2.1.2.zip)

i will write to the StarUML support team to put it into the extension registry
