### ISSUE TITLE
StarUML - Issue upgrading to latest version

### ISSUE THREAD

**Issue by oxoocoffee** [kkrisz1/staruml-reverse-db#48]
I just did try updating your package listed in StarUML 3.1.0 on my Mac OS X (10.14.6). Every time I update and restart StarUML I see that this package is available for update. I did try updating a few times. I am attaching the screenshots. Let me know if you need any information about my setup.

<img width="346" alt="StarUML 2019-07-19 17-47-48" src="https://user-images.githubusercontent.com/2259575/61569619-d1c40900-aa4d-11e9-958b-4d093d45871d.png">
<img width="358" alt="StarUML 2019-07-19 17-46-27" src="https://user-images.githubusercontent.com/2259575/61569620-d1c40900-aa4d-11e9-98fe-4c5661addc9d.png">

**Comment by kkrisz1** [comment]
Latest version: 1.0.11
Try to uninstall and install again
