### ISSUE TITLE
Can't generate ER Diagram for MySQL

### ISSUE THREAD

**Issue by MoroccanGeek** [kkrisz1/staruml-reverse-db#49]
i'm trying to generate ER diagram in MySQL DB, but it gives the error below:
![Screenshot_1](https://user-images.githubusercontent.com/39879193/64449625-47f0fd80-d0d8-11e9-92e1-d491b0d65ed8.jpg)

I'm using MySQL 8

**Comment by kkrisz1** [comment]
MySQL 8 has not been supported yet

**Comment by kkrisz1** [comment]
One more help:
pls check PR #54
