### ISSUE TITLE
StarUML v5 support?

### ISSUE THREAD

**Issue by shadiramadan** [kkrisz1/staruml-reverse-db#80]
Hello!

Do you plan on updating this to v5 any time soon?

**Comment by kkrisz1** [comment]
hi, 

no, it is not on the backlog right now.

why would it be necessary?
are there any incompatibilities?

i have just checked the [StarUML page](https://staruml.io/extensions). The extension should work from v3 up to v5 (_i have not tried it myself_)
![image](https://user-images.githubusercontent.com/19638316/166120529-a566f9a8-065e-4057-a95b-ccbe695c3c93.png)

pls let me know if i missed something

-krisz

**Comment by kkrisz1** [comment]
Hi,

I've hust released a new version: [v2.0.1](https://github.com/kkrisz1/staruml-reverse-db/releases/download/v2.0.1/kkrisz1.staruml-reverse-db-2.0.1.zip). It should support v5.
You could [install](https://docs.staruml.io/user-guide/managing-extensions) the extension manually if you would like to be an early user :)
Let me know if there are any issues.

_Note: v5 contains Node 16.x but PostgreSQL client was not compatible with it._
